apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: myghost
  name: myghost
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 2368
  selector:
    io.kompose.service: myghost
status:
  loadBalancer: {}
