apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: myghost
  name: myghost
spec:
  replicas: 3
  selector: 
    io.kompose.service: myghost

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: myghost
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        image: ghost
        name: myghost
        ports:
        - containerPort: 2368
        resources: {}
      restartPolicy: Always
status: {}
