---
apiVersion: v1
kind: Pod
metadata: 
  name: my-nginx1
spec:
  containers:
    - name: myng
      image: nginx
      volumeMounts:
        - name: my-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc1  
