---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-svc
  labels:
    app: mysql
spec:
  clusterIP: None
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels: 
    app: mysql
spec:
  replicas: 3
  serviceName: mysql-svc
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql

    spec: 
      containers:
        - name: mydb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: siva
          ports:
            - name: tcp
              protocol: TCP
              containerPort: 3306
          volumeMounts:
            - name: my-vol
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: my-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
            claimName: pvc1
