---
apiVersion: v1
kind: Service
metadata:
  name: pg-svc
spec:
  clusterIP: None
  ports:
    - name: tcp
      protocol: TCP
      port: 8080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-pg
  labels:
    app: pg
spec:
  replicas: 2
  serviceName: pg-svc
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      name: pg-pod
      labels:
        app: pg
    spec:
      containers:
        - name: mypg
          image: postgres
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: siva
            - name: POSTGRES_DB
              value: mydb
          ports:
            - name: tcp
              protocol: TCP
              containerPort: 5432
          volumeMounts:
            - name: pg-vol
              mountPath: /var/lib/pgsql/data
  volumeClaimTemplates:
    - metadata:
        name: pg-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        
