---
apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
spec:
  containers:
    - name: my-wp
      image: wordpress
      volumeMounts:
        - name: my-volume1
          mountPath: /var/www/html
  volumes:
    - name: my-volume1
      persistentVolumeClaim:
        claimName: my-pvc1  
