---
apiVersion: v1
kind: Pod
metadata:
  name: sql-pod
  labels:
    type: db
spec:
  containers:
    - name: mydb
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: siva
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave2
                operator: In
                values:
                  - sivaslave2

