---
apiVersion: v1
kind: Pod
metadata:
  name: sql-pod
  labels:
    creator: ibrahim
    service: db
spec:
  containers:
    - name: mydb
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: siva
      ports:
        - containerPort: 3306
          hostPort: 8888
...
