---
apiVersion: v1
kind: pod
metadata:
  name: sql-pod
  labels:
    creator: siva/ibrahim
    service: db
spec:
  containers:
    - name: mydb
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: siva
      ports:
        - containerPort: 3307
          hostPort: 8888 
  
...
