---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-ns
  labels:
    type: test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-deploy
  labels:
    type: proxy
    author: ibrahim
spec:
  replicas: 2
  selector:
    matchLabels:
      type: proxy
      author: ibrahim
  template:
    metadata:
      name: ng-pod
      namespace: prod-ns
      labels: 
        type: proxy 
        author: ibrahim
    spec: 
      containers:
        - name: mynginx
          image: nginx:latest
          ports: 
            - containerPort: 80
              hostPort: 8080
---

