---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  labels:
    type: db
spec:
  replicas: 4
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: sql-pod
      labels: 
        type: db 
        user: siva
    spec:
      containers:
        - name: mydb
          image: mysql 
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-secret
                  key: a
