---
apiVersion: v1
kind: Pod
metadata: 
  name: jen-pod
  labels:
    author: siva
spec:
  containers:
    - name: myjen
      image: jenkins/jenkins
      resources:
        requests:
          memory: "60Mi"
          cpu: "200m"
        limits:
          memory: "120Mi"
          cpu: "400m"
