---
kind: Pod
apiVersion: v1
metadata: 
  name: sql-pod
  labels:
    type: db
    user: siva
spec:
  containers:
    - name: mydb
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: a 
