---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: web
    author: siva
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8111
