---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: postgres-deployment
  labels:
    type: db
spec:
  replicas: 3
  selector:
    matchLabels:
      type: db

  template:
    metadata:
      name: pg-pod
      labels: 
        type: db
    spec:
      containers:
        - name: mydb
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-secret
                  key: a
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db
