---
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-rc
  labels:
    type: db
    author: siva
spec:
  replicas: 2
  template:
    metadata:
      name: pg-pod
      labels:
        type: db
        author: siva
    spec:
      containers:
        - name: mypg
          image: postgres
          env: 
           - name: POSTGRES_PASSWORD
             value: siva
           - name: POSTGRES_USER
             value: siva
           - name: POSTGRES_DB
             value: mydb
...
          
