---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sql-rc
  labels:
    type: db
    author: siva
spec:
  replicas: 2
  template:
    metadata:
      name: sql-pod
      labels:
        type: db
        author: siva
    spec:
      containers:
        -  name: mysql
           image: mysql
           env:
             - name: MYSQL_ROOT_PASSWORD
               value: siva
---
    
