---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: webserver
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 8080
  selector:
    author: ibrahim
    type: proxy

    
