---
apiVersion: v1
kind: Service
metadata:
  name: ghost-srv
  labels:
    type: CMS
spec:
  type: NodePort
  ports:
    - targetPort: 2368
      port: 2368
      nodePort: 30008
  selector:
    author: ghost
    type: CMS
    


