---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deploy
  labels:
    type: cms
spec:
  replicas: 3
  selector:
    matchLabels: 
      type: cms
  template:
    metadata:
      name: ghost-pod
      labels:
        type: cms
        author: siva
    spec:
      containers:
        - name: myghost
          image: ghost
          env:
            - name: NODE_ENV
              value: development
      tolerations:
        - key: slave1
          operator: Equal
          value: sivaslave
          effect: NoSchedule
        - key : slave2
          operator: Equal
          value: sivaslave2
          effect: NoSchedule
