---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  labels:
    type: cms
spec:
  containers:
    - name: myghost
      image: ghost
      env:
        - name: NODE_ENV
          value: development
  tolerations:
    - key: slave2
      operator: Equal
      value: sivaslave2
      effect: NoSchedule

