---
apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  labels:
    type: svc
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
        
  selector:
    type: https
    author: siva
