---
version: '3'
services:
  voting_app:
    image: dockersamples/examplevoting_vote
    ports:
      - 8080:80
    deploy:
      replicas: 2

  redis_app:
    image: redis
    ports:
      - 6380:6380

  worker_app:
    image: dockersamples/examplevotingapp_worker

  mydb:
    image: postgres
    environment:
       POSTGRES_PASSWORD: SIVA
    ports:
      - 5432:5432

  result_app:
    image: dockersamples/examplevotingapp_result
    ports:
      - 7070:80
    deploy:
      replicas: 2
