apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose1.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mydb
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mydb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mydb
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: SIVA
        image: postgres
        name: mydb
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
