apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose1.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-app
  name: redis-app
spec:
  ports:
  - name: "6380"
    port: 6380
    targetPort: 6380
  selector:
    io.kompose.service: redis-app
status:
  loadBalancer: {}
