apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose1.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-app
  name: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-app

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-app
    spec:
      containers:
      - image: redis
        name: redis-app
        ports:
        - containerPort: 6380
        resources: {}
      restartPolicy: Always
status: {}
