apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  labels:
    author: ibru
    type: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: mynginx
      labels:
        type: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 9090

