apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: db
    author: ibru
spec:
  containers:
    - name: db
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: ibrahim
    - name: nginx1
      image: nginx
          
