apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  namespace: test-is
  labels:
    author: ibru
    type: mine
spec:
  containers:
    - name: myhttpd
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 9090
  

